app:
  environment: dev
  name: sql-backend

logger:
  level: debug

database:
  host: postgres
  port: 5432
  username: postgres
  password: password
  name: free_diagrams_sql_db

http:
  host: 0.0.0.0
  port: 8080